#!/usr/bin/env bash

for f in \
  ag \
  bash \
  bash-completion \
  coreutils \
  fd \
  gh \
  git \
  git-gui \
  htop \
  node \
  nvim \
  pass \
  shellcheck \
  tmux \
  ; do
    brew install $f
done
