#!/usr/bin/env bash

files=(
.bash_profile
.bashrc
.bashrc.d
.gitconfig
.terraformrc
.tmux.conf
.vim
.vimrc
.config/nvim/coc-settings.json
.config/nvim/coc.vim
.config/nvim/init.vim
)

cd || exit

mkdir -p .config/nvim

for f in "${files[@]}"; do
  ln -sf "/Users/trott/code/github.com/trotttrotttrott/.files/$f" "$f"
done
