#!/usr/bin/env bash

files=(
.bash_profile
.bashrc
.gitconfig
.tmux.conf
.vim
.vimrc
.config/nvim/init.vim
)

cd

mkdir -p .config/nvim

for f in "${files[@]}"; do
  ln -sf "/Users/trott/code/github.com/trotttrotttrott/.files/$f" "$f"
done
