#!/usr/bin/env bash

for f in \
  ag \
  bash \
  bash-completion \
  bind \
  coreutils \
  diffutils \
  fd \
  gh \
  git \
  git-gui \
  htop \
  jsonnet \
  kubectx \
  kubernetes-cli \
  nmap \
  node \
  nvim \
  pass \
  s3cmd \
  shellcheck \
  tmux \
  wget \
  \
  awscli \
  azurecli \
  '--cask gcloud-cli' \
  ; do
    brew install "$f"
done
