#!/usr/bin/env bash

for t in \
  hashicorp/tap \
  ; do
    brew tap $t
done

for f in \
  ag \
  bash \
  bash-completion \
  bind \
  coreutils \
  diffutils \
  fd \
  gh \
  git \
  git-gui \
  hashicorp/tap/terraform \
  htop \
  jsonnet \
  kubectx \
  kubernetes-cli \
  nmap \
  node \
  nvim \
  pass \
  s3cmd \
  shellcheck \
  tmux \
  ; do
    brew install $f
done
