#!/usr/bin/env bash

files=(
.agignore
.bash_profile
.bashrc.d
.gitconfig
.terraformrc
.tmux.conf
.vim
.vimrc
.config/nvim/coc-settings.json
.config/nvim/coc.vim
.config/nvim/init.vim
.config/ghostty/config
)

cd || exit

mkdir -p .config/nvim
mkdir -p .config/ghostty

files_path='/Users/trott/code/github.com/trotttrotttrott/.files'

ln -sfh "$files_path/.bashrc" 'mac/.bashrc'

for f in "${files[@]}"; do
  ln -sfh "$files_path/$f" "$f"
done
